/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import CheeseCoinCore.CurrentMember;
import CheeseCoinCore.GeneralExceptionHandler;
import CheeseCoinCore.GenerateGenesis;
import JsonParser.JsonParserCustom;
import MessageSender.MessageQueueSingleton;
import MessageSender.MessageSender;
import Model.RequestModel;
import Model.Sender_M;
import Model.Transaction_M;
import dataAccess.Transaction_DAO;
import enums.ReqCommand;
import enums.RequestType;
import java.net.Socket;
import java.net.SocketTimeoutException;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import ConfigurationSetting.ConfigSetting;
import requestMaker.GemMemberList_RM;
import requestMaker.GetCheeseList_RM;
import requestMaker.GetTransactionList_RM;
import requestMaker.InformToServer;
import requestMaker.NewTransaction_RM;

/**
 *
 * @author user
 */
public class Main_Member extends javax.swing.JFrame {

    /**
     * Creates new form Main_Member
     */
    public Main_Member() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGenGenesis = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblChee = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnGtCheseChain = new javax.swing.JButton();
        btnViewCheese = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnViewTranction = new javax.swing.JButton();
        btnDeathTest = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnUpdateCheeseChain = new javax.swing.JButton();
        btnUpdateTran = new javax.swing.JButton();
        btnConfig = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGenGenesis.setText("Generate Genesis Cheese");
        btnGenGenesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenGenesisActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        lblChee.setFont(new java.awt.Font("Tele-Marines", 1, 18)); // NOI18N
        lblChee.setText("Cheese-Coin Companion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(lblChee)
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblChee)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButton1.setText("New Transaction");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("TestMember");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnGtCheseChain.setText("Get Cheese Chain");
        btnGtCheseChain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGtCheseChainActionPerformed(evt);
            }
        });

        btnViewCheese.setText("View Cheese");
        btnViewCheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCheeseActionPerformed(evt);
            }
        });

        jButton4.setText("Test Tracker");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnViewTranction.setText("View Transaction");
        btnViewTranction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTranctionActionPerformed(evt);
            }
        });

        btnDeathTest.setText("Death Mem Test");
        btnDeathTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeathTestActionPerformed(evt);
            }
        });

        jButton2.setText("Register Member");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnGtCheseChain, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnViewTranction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeathTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewCheese, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeathTest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewTranction)
                .addGap(2, 2, 2)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewCheese)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGtCheseChain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );

        btnUpdateCheeseChain.setText("Update Cheese Chain");
        btnUpdateCheeseChain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCheeseChainActionPerformed(evt);
            }
        });

        btnUpdateTran.setText("Update Transaction");
        btnUpdateTran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTranActionPerformed(evt);
            }
        });

        btnConfig.setText("Config");
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnGenGenesis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdateCheeseChain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdateTran, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConfig, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnConfig)
                        .addGap(27, 27, 27)
                        .addComponent(btnGenGenesis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateCheeseChain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateTran)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        Transaction_M tran=new Transaction_M();
        Transaction_DAO tranDao=new Transaction_DAO();
        Transaction_M lastTran=tranDao.getLastTransaction();
        if(lastTran==null)
        {
             lastTran=new Transaction_M();
             lastTran.setPublic_transaction_id(0);
        }   
            
        Timestamp ts=new Timestamp(System.currentTimeMillis());  
        Date date=ts;
        
        Sender_M sender=new Sender_M( );
        sender.setAmount(12);
        sender.setDate_time(date);
        sender.setSender_account_id(2);
        sender.setReceiver_account_id(2);
        sender.setPublic_transaction_id(lastTran.getPublic_transaction_id()+1);
        
        List<Sender_M> senderList=new ArrayList<Sender_M>();
        senderList.add(sender);
        tran.setAmount(20);         
        tran.setDate_time(date);
        tran.setTime_stamp(date);
        tran.setPublic_transaction_id(1);
        tran.setPublic_transaction_id(lastTran.getPublic_transaction_id()+1);
        tran.setStatus("waiting");
        tran.setReceiver_account_id(2);
        tran.setSenderList(senderList);

        
            //check whether already exist
//            int result =tranDao.checkExistByPublicID(this.transaction.getPublic_transaction_id());
            
//         
        NewTransaction_RM tranRM=new NewTransaction_RM(tran);
        tranRM.initate(tran);
        
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        GemMemberList_RM reg=new GemMemberList_RM();
        reg.initate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Test functions:
        CurrentMember cur=new CurrentMember();
        
        String ip=cur.getIp();
        int port=cur.getPort();
        int requestingCount=0;
        RequestModel<String> req=new RequestModel(RequestType.GET.toString(),ReqCommand.REQ_TEST.toString());
        try 
        {

           Socket socket= new Socket(ip,port);
           MessageQueueSingleton messQueue=MessageQueueSingleton.getInstance();
           HashMap<String,Object> mesg=new HashMap<String,Object>();
           mesg.put("socket",socket);
           mesg.put("request",req);
           System.out.println(mesg);
           
           MessageSender mesgSender=new MessageSender();
           new Thread(mesgSender).start();//starting queue
           messQueue.putQueue(mesg);
           System.out.print("QUEUE IS : "+messQueue);

           
        }
        catch(Exception ex)
        {
            System.out.println(ex.getMessage());
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        //testing tracker
       GemMemberList_RM register=new GemMemberList_RM();
       register.initate();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnGenGenesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenGenesisActionPerformed
        // TODO add your handling code here:
        GenerateGenesis gen=new GenerateGenesis();
        int result=gen.generateGenesis();
        if(result==1)
        {
            JOptionPane.showMessageDialog(this, "Successfully Created");
            
        }
        else if(result ==2)
        {
         JOptionPane.showMessageDialog(this, "Genesis Cheese Already created");

        }
            
    }//GEN-LAST:event_btnGenGenesisActionPerformed

    private void btnViewTranctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTranctionActionPerformed
        // TODO add your handling code here:
        View_Transaction viewT=new View_Transaction();
        viewT.show();
    }//GEN-LAST:event_btnViewTranctionActionPerformed

    private void btnGtCheseChainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGtCheseChainActionPerformed
        // TODO add your handling code here:
        String ip="127.0.0.1";
        int port=8222;
        int requestingCount=0;
        RequestModel<String> req=new RequestModel(RequestType.GET.toString(),ReqCommand.REQ_TEST.toString());
        try 
        {

           Socket socket= new Socket(ip,port);
           MessageQueueSingleton messQueue=MessageQueueSingleton.getInstance();
           HashMap<String,Object> mesg=new HashMap<String,Object>();
           mesg.put("socket",socket);
           mesg.put("request",req);
           System.out.println(mesg);
           
           MessageSender mesgSender=new MessageSender();
           new Thread(mesgSender).start();//starting queue
           messQueue.putQueue(mesg);
           System.out.print("QUEUE IS : "+messQueue);

           
        }
        catch(Exception ex)
        {
            System.out.println(ex.getMessage());
        }
        
    }//GEN-LAST:event_btnGtCheseChainActionPerformed

    private void btnDeathTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeathTestActionPerformed
        
        // Test functions:
        String ip="66.66.66.66";
        int port=6666;
        int requestingCount=0;
        RequestModel<String> req=new RequestModel(RequestType.GET.toString(),ReqCommand.REQ_TEST.toString());
        try 
        {

            try {
                 Socket socket= new Socket(ip,port);
            } catch (java.net.ConnectException e) {
                System.out.println("Timeout Reached");
//                InformToServer inform=new InformToServer();
//                inform.inform(ip, port);
                GeneralExceptionHandler exc=new GeneralExceptionHandler(ip, port);
                exc.handleException(e);
            }
           
        }
        catch(Exception ex)
        {
            System.out.println(ex.getMessage());
        }
        
        
    }//GEN-LAST:event_btnDeathTestActionPerformed

    private void btnViewCheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCheeseActionPerformed
        // TODO add your handling code here:
        ViewCheese cheeselist=new ViewCheese();
        cheeselist.show();
                
    }//GEN-LAST:event_btnViewCheeseActionPerformed

    private void btnUpdateCheeseChainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCheeseChainActionPerformed
        // TODO add your handling code here:
        GetCheeseList_RM get=new GetCheeseList_RM();
        get.initate();
    }//GEN-LAST:event_btnUpdateCheeseChainActionPerformed

    private void btnUpdateTranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTranActionPerformed
        // TODO add your handling code here:
        GetTransactionList_RM get=new GetTransactionList_RM();
        get.initate();
    }//GEN-LAST:event_btnUpdateTranActionPerformed

    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        SwingUtilities.invokeLater(new Runnable() {
			@Override
			public void run() {
				new ConfigSetting();
			}
		});
    }//GEN-LAST:event_btnConfigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnDeathTest;
    private javax.swing.JButton btnGenGenesis;
    private javax.swing.JButton btnGtCheseChain;
    private javax.swing.JButton btnUpdateCheeseChain;
    private javax.swing.JButton btnUpdateTran;
    private javax.swing.JButton btnViewCheese;
    private javax.swing.JButton btnViewTranction;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblChee;
    // End of variables declaration//GEN-END:variables
}
