/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Cheese_M;
import Model.Transaction_M;
import dataAccess.Cheese_DAO;
import dataAccess.Transaction_DAO;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import proof_of_work.SingletonProofOfWorkInstance;

/**
 *
 * @author user
 */
public class View_Transaction extends javax.swing.JFrame {

     private DefaultTableModel tblModel;
     
    public View_Transaction() {
        initComponents();
        List<Transaction_M> tranList=getAllTransaction();
        tblModel=new DefaultTableModel();
        tblViewTran.setModel(tblModel);
         tblModel.addColumn("T_ID");
        tblModel.addColumn("T_Amount");
        tblModel.addColumn("T_Date");
        tblModel.addColumn("T_Pubic ID");
        tblModel.addColumn("Rece_Acnt_ID");
        tblModel.addColumn("_Status");
         for(Transaction_M p:tranList){ //For loop will take one patient by one
            tblModel.addRow(new Object[]{p.getTransaction_id(),
                p.getAmount(),p.getDate_time(),
                p.getPublic_transaction_id(),
                p.getReceiver_account_id(),
                p.getStatus()});
        }
       
    }

    public List<Transaction_M> getAllTransaction()
    {
        Transaction_DAO trandao=new Transaction_DAO();
        List<Transaction_M> tranlist=trandao.getAll();
        return tranlist;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewTran = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblViewTran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblViewTran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewTranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblViewTran);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jButton1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblViewTranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewTranMouseClicked
        // TODO add your handling code here:
        
        JTable source = (JTable)evt.getSource();
            int row = source.rowAtPoint( evt.getPoint() );
            int column = source.columnAtPoint( evt.getPoint() );
            String s=source.getModel().getValueAt(row, column)+"";

           int result= JOptionPane.showConfirmDialog(this, "Do you want to mine this");
           if(result==0)
           {
              String status= source.getModel().getValueAt(row, 5).toString();
              if(status.equals("waiting"))
              {
                int publicTranID=(int) source.getModel().getValueAt(row, 3);
                Transaction_DAO tranDao=new Transaction_DAO();
                Transaction_M tran=tranDao.getOneByPublicTranID(publicTranID);
                SingletonProofOfWorkInstance pow=SingletonProofOfWorkInstance.getInstance();
                HashMap<String, Object> obj=new HashMap<String, Object>();
                obj.put("transaction", tran);
                pow.putQueue(obj);  
               
              }
              else if (status.equals("mined"))
              {
              JOptionPane.showMessageDialog(this, "Already Mined");
                
              }
              else
              {
                  JOptionPane.showMessageDialog(this, "Already Mined");
              }
           } 
    }//GEN-LAST:event_tblViewTranMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblViewTran;
    // End of variables declaration//GEN-END:variables
}
